name: Build & test

on:
  push:
    tags-ignore: 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Go environment
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.26.1'

    - name: Download dependencies
      run: go mod download

    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: v2.11.3

    - name: Build
      run: go build -v ./...

    - name: Check formatting
      run: |
        go install mvdan.cc/gofumpt@v0.11.0
        test -z "$(gofumpt -extra -l .)" || { gofumpt -extra -d .; exit 1; }

    - name: Test
      run: go test -race -shuffle=on -v ./...
